@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg1NDk0NTAwLCJpYXQiOjE3ODU0OTQyMDAsImp0aSI6ImUwMTMzMWRiNTYzZTRkNGViZGZkODFlNDE5NDI4MWIwIiwidXNlcl9pZCI6IjEifQ.9G0a8LdnsTEkxFQ9FQvQ6rK4cQekgro0ZOvlg5Bkmm4
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NTU4MDYwMCwiaWF0IjoxNzg1NDk0MjAwLCJqdGkiOiIzZmEzMmE5MTMxNzg0MzJhOTViYmIyZjUwMzM2OGUwMCIsInVzZXJfaWQiOiIxIn0.ZLbgwyJS6poBkKjZ7xcU12WXiKnkZgLgvfqGwPqLlQ0

POST {{baseUrl}}/api/token/
Content-Type: application/json

{
    "username": "alice",
    "password": "motdepasse-demo"
}

###

POST {{baseUrl}}/api/avis/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "commentaire": "Commentaire de test nouveau",
    "rating": 5,
    "livre": 1
}


###
GET {{baseUrl}}/api/avis/
###
# test update non connecté

PUT {{baseUrl}}/api/avis/1/
Content-Type: application/json

{
    "commentaire": "Commentaire de test updaté",
    "rating": 5,
    "livre": 1

}

###
# test update connecté

PUT {{baseUrl}}/api/avis/1/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "commentaire": "Commentaire de test updaté",
    "rating": 5,
    "livre": 1
}

###

PATCH {{baseUrl}}/api/avis/1/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rating": 4
}
###

DELETE {{baseUrl}}/api/avis/1/
Authorization: Bearer {{token}}
###

POST {{baseUrl}}/api/avis/1/like/
Content-Type: application/json
Authorization: Bearer {{token}}
