### Scénario de test pour les permissions sur les avis en étant pas le créateur de l'avis
@baseUrl = http://localhost:8000
@tokencreator = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg1NDAzNjczLCJpYXQiOjE3ODU0MDMzNzMsImp0aSI6ImY4MmI4YWQ1NGQ5ZjQ5Yzk4OGQ0ZDkyMGY2Y2QxMTU4IiwidXNlcl9pZCI6IjIifQ.Q1YCA5SOk5J8wLEcGyvRtv5nAaP9xp_tK0S19YoG9hU
@refreshcreator = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NTQyNDI5MywiaWF0IjoxNzg1MzM3ODkzLCJqdGkiOiJmNjcyZmJmOTI2MTI0YzUzYmIyYzcwMDEzZDE3NzBhMSIsInVzZXJfaWQiOiIxIn0.1kVfzilSXxawthUsHBYebvU6SjSqw-JEudtLWj7UIig

### setup création de l'avis par le créateur
POST {{baseUrl}}/api/token/
Content-Type: application/json

{
    "username": "alice",
    "password": "motdepasse-demo"
}

###

POST {{baseUrl}}/api/avis/
Content-Type: application/json
Authorization: Bearer {{tokencreator}}

{
    "user": 2,
    "commentaire": "Commentaire de test",
    "rating": 5,
    "livre": 1
}

### like un avis en étant le créateur de l'avis
POST {{baseUrl}}/api/avis/1/like/
Content-Type: application/json
Authorization: Bearer {{tokencreator}}

###
@tokentestor = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg1NDAzNjQ3LCJpYXQiOjE3ODU0MDMzNDcsImp0aSI6ImU3YzA4NjgyMGFmNDRkNDE4YWZmMzRkNWNmM2QwMDI0IiwidXNlcl9pZCI6IjMifQ.MdEGGVUPhWUoogt8lxz9NpTwjf4PVTJKM9vNW9Du4DE

POST {{baseUrl}}/api/token/
Content-Type: application/json

{
    "username": "chapeau",
    "password": "demo-motdepasse"
}
###

PUT {{baseUrl}}/api/avis/1/
Content-Type: application/json
Authorization: Bearer {{tokentestor}}

{
    "user": 2,
    "commentaire": "Commentaire de test updaté",
    "rating": 5,
    "livre": 1
}

###

DELETE {{baseUrl}}/api/avis/1/
Content-Type: application/json
Authorization: Bearer {{tokentestor}}

###

PATCH {{baseUrl}}/api/avis/1/
Content-Type: application/json
Authorization: Bearer {{tokentestor}}

{
    "commentaire": "Commentaire de test updaté"
}



### like un avis en étant pas le créateur de l'avis
POST {{baseUrl}}/api/avis/1/like/
Content-Type: application/json
Authorization: Bearer {{tokentestor}}